language: objective-c

osx_image: xcode10.1
env:
  matrix:
    - TEST_SDK=iphonesimulator13.6 OS=13.6 NAME='iPhone Xs Max'
  
script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project AldaSwiftLib.xcodeproj -scheme AldaSwiftLib -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES
